import fs from 'node:fs';

// Names, constants and addresses from the pret/pokered disassembly (generated by `npm run setup`).

interface Generated {
  maps: Record<string, { name: string; width: number; height: number }>;
  events: Record<string, number>;
  charmap: Record<string, string>;
  sprites: Record<string, string>;
  sym: Record<string, number>;
}

let cached: Generated | undefined;
function data(): Generated {
  if (!cached) {
    if (!fs.existsSync('data/pokered.json')) throw new Error('data/pokered.json is missing: run `npm run setup` first');
    cached = JSON.parse(fs.readFileSync('data/pokered.json', 'utf8')) as Generated;
  }
  return cached;
}

/** Address of a pokered symbol: WRAM/HRAM symbols are CPU addresses, ROM symbols are flat file offsets. */
export function sym(name: string): number {
  const a = data().sym[name];
  if (a === undefined) throw new Error(`unknown symbol ${name}`);
  return a;
}

export function symbols(): Record<string, number> {
  return data().sym;
}

export function mapName(id: number): string {
  return data().maps[id]?.name ?? `MAP_${id}`;
}

export function mapId(name: string): number {
  const e = Object.entries(data().maps).find(([, m]) => m.name === name);
  if (!e) throw new Error(`unknown map ${name}`);
  return +e[0];
}

export function allMaps() {
  return data().maps;
}

export function eventBit(name: string): number {
  const bit = data().events[name];
  if (bit === undefined) throw new Error(`unknown event ${name}`);
  return bit;
}

export function charmap(): Record<string, string> {
  return data().charmap;
}

export function spriteName(id: number): string {
  return data().sprites[id] ?? `SPRITE_${id}`;
}

/** "ROUTE_22_GATE" -> "Route 22 Gate", for text Jev reads. */
export function prettyMap(name: string): string {
  return name
    .split('_')
    .map((w) => (/^\d+F$|^B\d+F$|^SS$|^PC$/.test(w) ? w : w.charAt(0) + w.slice(1).toLowerCase()))
    .join(' ')
    .replace(/s\b(?= (Lab|House|Room|Gym))/, "'s")
    .replace(/^Oaks /, "Oak's ");
}
